PLATFORMS = [
    "Akulaku",
    "Kredivo",
    "Shopee PayLater",
    "GoPay Later",
    "Dana",
    "SPayLater",
    "Home Credit",
    "FIF",
    "Adira",
    "Kredit Pintar",
    "EasyCash",
    "Danamon",
    "Mandiri",
    "BCA",
    "BNI",
    "BRI",
    "CIMB Niaga",
    "Maybank",
    "Permata",
    "Pinjaman Teman",
    "Pinjaman Keluarga",
    "Cash / Tunai",
    "Lainnya",
]

CATEGORIES = [
    "pinjol",
    "paylater",
    "kredit",
    "bank",
    "teman",
    "cash",
    "lainnya",
]
